import test from 'node:test';import assert from 'node:assert/strict';import {reviewRecentCatchall,reviewText} from './mail-review.mjs';
const config={mcpUrl:'https://mcp.zoho.com/mcp/SYNTHETIC_SECRET/message',primaryEmail:'owner@example.test',catchallFolderId:'456'};
const schema=(name,properties={},required=[])=>({name,inputSchema:{type:'object',properties,required},annotations:{readOnlyHint:true}});
const tools=[schema('ZohoMail_getMailAccounts'),schema('ZohoMail_listEmails',{path_variables:{type:'object',properties:{accountId:{type:'string'}},required:['accountId']},query_params:{type:'object',properties:{folderId:{type:'string'},limit:{type:'integer',format:'int32'},start:{type:'integer',format:'int32'},fields:{type:'string'}},required:['fields']}},['path_variables','query_params']),schema('ZohoMail_getMessageContent',{path_variables:{type:'object',properties:{accountId:{type:'string'},folderId:{type:'string'},messageId:{type:'string'}},required:['accountId','folderId','messageId']},query_params:{type:'object',properties:{includeBlockContent:{type:'boolean'}}}},['path_variables'])];
function fixture({wrongOwner=false,write=false,wrongFolder=false,oversize=false}={}){const calls=[];const clientFactory=()=>({connect:async()=>{},close:async()=>{},listTools:async()=>({tools:[...tools,...(write?[schema('ZohoMail_sendEmail')]:[])]}),callTool:async({name,arguments:args})=>{
 calls.push({name,args});let data;
 if(name==='ZohoMail_getMailAccounts')data={data:[{accountId:'123',primaryEmailAddress:wrongOwner?'other@example.test':config.primaryEmail}]};
 if(name==='ZohoMail_listEmails'){assert.equal(args.path_variables.accountId,'123');assert.equal(args.query_params.folderId,'456');assert.equal(args.query_params.limit,5);data={data:Array.from({length:oversize?6:5},(_,i)=>({messageId:String(i+1),folderId:wrongFolder?'999':'456',subject:i===0?'VPN outage':'Ordinary newsletter',fromAddress:'sender@example.test',receivedTime:'1791140000000'}))};}
 if(name==='ZohoMail_getMessageContent'){assert.equal(args.path_variables.folderId,'456');assert.equal(args.query_params.includeBlockContent,false);data={data:{content:'<div>VPN unavailable. https://example.test/token/SENSITIVE_LINK access_token=PRIVATE_TOKEN</div>'}};}
 return {content:[{type:'text',text:JSON.stringify({data:{status:{code:200},...data}})}]};
 }});return{clientFactory,calls};}
test('bounded catchall pages deduplicate IDs and read content only for IT candidates',async()=>{const f=fixture();const result=await reviewRecentCatchall(config,f);assert.equal(result.status,'bounded_review_complete');assert.equal(result.ownerMatched,true);assert.equal(result.coverage.listed,10);assert.equal(result.coverage.unique,5);assert.equal(result.coverage.contentRead,1);assert.equal(result.coverage.repliesChecked,false);assert.equal(result.candidates.length,1);assert(!JSON.stringify(result).includes('PRIVATE_TOKEN'));assert(!JSON.stringify(result).includes('SENSITIVE_LINK'));assert(!JSON.stringify(result).includes('SYNTHETIC_SECRET'));assert.deepEqual(f.calls.filter(c=>c.name==='ZohoMail_listEmails').map(c=>c.args.query_params.start),[1,6]);});
test('wrong owner/writes stop before mail; wrong folder or oversized page fails closed',async()=>{for(const options of [{wrongOwner:true},{write:true}]){const f=fixture(options);assert.equal((await reviewRecentCatchall(config,f)).ok,false);assert(!f.calls.some(c=>c.name==='ZohoMail_listEmails'));}for(const options of [{wrongFolder:true},{oversize:true}])assert.equal((await reviewRecentCatchall(config,fixture(options))).ok,false);});
test('HTML is never rendered or fetched, and excerpts are bounded',()=>{assert.equal(reviewText('<script>alert(1)</script><p>Hello</p>'),'Hello');assert.equal(reviewText('x'.repeat(10000)).length,4000);});
