import test from 'node:test';import assert from 'node:assert/strict';import {ownerReadCheck} from './owner-read-check.mjs';
const config={mcpHost:'mail-123456.zohomcp.com',mcpUrl:'https://mail-123456.zohomcp.com/mcp/SYNTHETIC_ENDPOINT_KEY/message',primaryEmail:'owner@example.test',folderId:'456'};
test('observed nested namespace verifies owner and sends only messageId projection with limit one',async()=>{
 const fixture=readFixture({nested:true});const result=await ownerReadCheck(config,fixture);assert.equal(result.status,'read_verified');assert.equal(result.ownerMatched,true);assert.equal(result.messageCount,1);
 const mismatch=readFixture({nested:true,wrongOwner:true});assert.equal((await ownerReadCheck(config,mismatch)).status,'owner_binding_unverified');assert(!mismatch.calls.some(c=>c.params?.name==='ZohoMail_listEmails'));
 const unsupported=readFixture({nested:true,unsupported:true});assert.equal((await ownerReadCheck(config,unsupported)).status,'list_schema_unsupported');assert(!unsupported.calls.some(c=>c.method==='tools/call'));
 assert.equal((await ownerReadCheck(config,readFixture({nested:true,bigList:true}))).status,'message_bound_unverified');
 assert(!JSON.stringify(result).includes('SYNTHETIC_ENDPOINT_KEY'));assert(!JSON.stringify(result).includes('PRIVATE_SUBJECT'));
});
const tool=(name,properties={},required=[])=>({name,inputSchema:{type:'object',properties,required},annotations:{readOnlyHint:true}});
export function readFixture({unknown=false,wrongOwner=false,bigList=false,auth=false,unsupported=false,paginated=false,namespaced=false,nested=false,enveloped=false,providerError=false}={}){
 const calls=[];const fetcher=async(url,init)=>{assert.equal(String(url),config.mcpUrl);assert.equal(init.redirect,'manual');if(init.method==='GET')return new Response(null,{status:405});if(init.method==='DELETE')return new Response(null,{status:204});const rpc=JSON.parse(init.body);calls.push(rpc);if(auth)return new Response(config.mcpUrl,{status:401});if(rpc.method==='notifications/initialized')return new Response(null,{status:202});let result;
 if(rpc.method==='initialize')result={protocolVersion:'2025-03-26',capabilities:{tools:{}},serverInfo:{name:config.mcpUrl,version:'synthetic'}};
 if(rpc.method==='tools/list')result=rpc.params?.cursor?{tools:[tool('sendEmail')]}:{tools:[tool(nested?'ZohoMail_getMailAccounts':'getMailAccounts'),nested?tool('ZohoMail_listEmails',{path_variables:{type:'object',required:['accountId'],properties:{accountId:{type:'string'}}},query_params:{type:'object',required:['fields'],properties:{fields:{type:'string'},limit:{type:unsupported?'string':'integer'},start:{type:'integer'},folderId:{type:'string'}}}},['path_variables','query_params']):tool(namespaced?'ZohoMail_listEmails':'listEmails',{accountId:{type:'string'},limit:{type:unsupported?'string':'integer'},start:{type:'integer'},folderId:{type:'string'}},['accountId','limit']),...(unknown?[tool(unknown===true?'sendEmail':unknown)]:[])],...(paginated?{nextCursor:'PRIVATE_CURSOR'}:{})};
 if(rpc.method==='tools/call'){if(['getMailAccounts','ZohoMail_getMailAccounts'].includes(rpc.params.name))result={content:[{type:'text',text:JSON.stringify({data:[{accountId:'123',primaryEmailAddress:wrongOwner?'other@example.test':config.primaryEmail,access_token:'SYNTHETIC_TOKEN'}]})}]};else{assert.equal(rpc.params.name,namespaced||nested?'ZohoMail_listEmails':'listEmails');assert.deepEqual(rpc.params.arguments,nested?{path_variables:{accountId:'123'},query_params:{fields:'messageId',limit:1,start:1,folderId:'456'}}:{accountId:'123',limit:1,start:1,folderId:'456'});result={content:[{type:'text',text:JSON.stringify({status:{code:200},data:Array.from({length:bigList?2:1},()=>({messageId:'789',subject:'PRIVATE_SUBJECT',content:'PRIVATE_CONTENT',endpoint:config.mcpUrl}))})}]}}};
 if(enveloped&&rpc.method==='tools/call'&&rpc.params.name.endsWith('listEmails')){const mail=JSON.parse(result.content[0].text);if(providerError)mail.status.code=500;result.content[0].text=JSON.stringify({data:mail});}
 return Response.json({jsonrpc:'2.0',id:rpc.id,result});};return{fetcher,calls};
}
test('observed Mail API envelope verifies bounded IDs and refuses inner errors or excess rows',async()=>{
 assert.equal((await ownerReadCheck(config,readFixture({nested:true,enveloped:true}))).status,'read_verified');
 assert.equal((await ownerReadCheck(config,readFixture({nested:true,enveloped:true,bigList:true}))).status,'message_bound_unverified');
 assert.equal((await ownerReadCheck(config,readFixture({nested:true,enveloped:true,providerError:true}))).status,'provider_tool_error');
});
test('real SDK account binding and one bounded list disclose only safe metadata/status',async()=>{const fixture=readFixture();const result=await ownerReadCheck(config,fixture);assert.equal(result.status,'read_verified');assert.equal(result.ownerMatched,true);assert.equal(result.messageCount,1);const output=JSON.stringify(result);for(const privateValue of ['123','456','789',config.primaryEmail,config.mcpUrl,'SYNTHETIC_TOKEN','PRIVATE_SUBJECT','PRIVATE_CONTENT'])assert(!output.includes(privateValue));assert.deepEqual(fixture.calls.filter(c=>c.method==='tools/call').map(c=>c.params.name),['getMailAccounts','listEmails']);});
test('write inventory and unsupported schema cause no mailbox invocation',async()=>{for(const options of [{unknown:true},{unsupported:true}]){const fixture=readFixture(options);const result=await ownerReadCheck(config,fixture);assert.equal(result.ok,false);assert.equal(fixture.calls.some(c=>c.method==='tools/call'),false);}});
test('wrong owner cannot reach message list; ignored bound does not count as success',async()=>{const mismatch=readFixture({wrongOwner:true});assert.equal((await ownerReadCheck(config,mismatch)).status,'owner_binding_unverified');assert.equal(mismatch.calls.some(c=>c.params?.name==='listEmails'),false);assert.equal((await ownerReadCheck(config,readFixture({bigList:true}))).status,'message_bound_unverified');});
test('HTTP authorization challenge produces fixed category and does not register or leak endpoint',async()=>{const result=await ownerReadCheck(config,readFixture({auth:true}));assert.equal(result.status,'mcp_authorization_required');assert(!JSON.stringify(result).includes('SYNTHETIC'));});
test('unknown credential-shaped tool names and later-page writes cannot escape policy or leak cursor',async()=>{
 const unknown=await ownerReadCheck(config,readFixture({unknown:'SYNTHETIC_ENDPOINT_KEY'}));assert.equal(unknown.status,'server_not_readonly');assert(!JSON.stringify(unknown).includes('SYNTHETIC_ENDPOINT_KEY'));assert.equal(unknown.tools.at(-1).name,'[REDACTED TOOL NAME]');
 const pages=readFixture({paginated:true});const result=await ownerReadCheck(config,pages);assert.equal(result.status,'server_not_readonly');assert.equal(pages.calls.filter(c=>c.method==='tools/list').length,2);assert.equal(pages.calls.some(c=>c.method==='tools/call'),false);assert(!JSON.stringify(result).includes('PRIVATE_CURSOR'));
});
test('observed namespaced read alias keeps exact runtime name and validates schema/owner',async()=>{
 const fixture=readFixture({namespaced:true});const result=await ownerReadCheck(config,fixture);assert.equal(result.status,'read_verified');assert.equal(result.tools[1].name,'ZohoMail_listEmails');assert.equal(result.tools[1].schema,'compatible');assert(fixture.calls.some(c=>c.params?.name==='ZohoMail_listEmails'));
 const mismatch=readFixture({namespaced:true,wrongOwner:true});assert.equal((await ownerReadCheck(config,mismatch)).status,'owner_binding_unverified');assert(!mismatch.calls.some(c=>c.params?.name==='ZohoMail_listEmails'));
 assert.equal((await ownerReadCheck(config,readFixture({namespaced:true,unsupported:true}))).status,'list_schema_unsupported');
 const writes=readFixture({namespaced:true,unknown:'ZohoMail_sendEmail'});assert.equal((await ownerReadCheck(config,writes)).status,'server_not_readonly');assert(!writes.calls.some(c=>c.method==='tools/call'));
});
